# This is the DEV workflow.
# Run this Action on creating a new tag matching "<version>-b<build>"
# e.g., 3.7-b1
name: Build support package
on:
  push:
    tags:
    - '*-b*'

jobs:
  config:
    name: Build vars
    runs-on: macOS-latest
    outputs:
      TAG: ${{ steps.build-vars.outputs.TAG }}
      BUILD_NUMBER: ${{ steps.build-vars.outputs.BUILD_NUMBER }}
<<<<<<< HEAD
      PYTHON_VERSION: ${{ steps.version-details.outputs.PYTHON_VERSION }}
      BZIP2_VERSION: ${{ steps.version-details.outputs.BZIP2_VERSION }}
      XZ_VERSION: ${{ steps.version-details.outputs.XZ_VERSION }}
      LIBFFI_VERSION: ${{ steps.version-details.outputs.LIBFFI_VERSION }}
      OPENSSL_VERSION: ${{ steps.version-details.outputs.OPENSSL_VERSION }}
    strategy:
      matrix:
        target: ['macOS', 'iOS']
    steps:
    - uses: actions/checkout@v4
=======
>>>>>>> c8da2e9e3daccf602ab89bd73b7baad1b583da80

    steps:
    - name: Set Build Variables
      id: build-vars
      env:
        TAG_NAME: ${{ github.ref }}
      run: |
        export TAG=$(basename $TAG_NAME)
        export BUILD_NUMBER="${TAG#*-}"

        echo "TAG=${TAG}" | tee -a ${GITHUB_OUTPUT}
        echo "BUILD_NUMBER=${BUILD_NUMBER}" | tee -a ${GITHUB_OUTPUT}

  ci:
    name: CI
    needs: [ config ]
    uses: ./.github/workflows/ci.yaml
    with:
      build-number: ${{ needs.config.outputs.BUILD_NUMBER }}

  make-release:
    name: Make Release
    runs-on: ubuntu-latest
    needs: [ config, ci ]
    steps:
    - name: Get build artifacts
      uses: actions/download-artifact@v4.1.8
      with:
        pattern: Python-*
        path: dist
        merge-multiple: true

    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        name: ${{ needs.ci.outputs.PYTHON_VER }}-${{ needs.config.outputs.BUILD_NUMBER }}
        tag: ${{ needs.ci.outputs.PYTHON_VER }}-${{ needs.config.outputs.BUILD_NUMBER }}
        draft: true
        body: |
          Build ${{ needs.config.outputs.BUILD_NUMBER }} of the BeeWare support package for Python ${{ needs.ci.outputs.PYTHON_VER }}.

          Includes:
          * Python ${{ needs.ci.outputs.PYTHON_VERSION }}
          * BZip2 ${{ needs.ci.outputs.BZIP2_VERSION }}
          * libFFI ${{ needs.ci.outputs.LIBFFI_VERSION }}
          * mpdecimal ${{ needs.ci.outputs.MPDECIMAL_VERSION }}
          * OpenSSL  ${{ needs.ci.outputs.OPENSSL_VERSION }}
          * XZ ${{ needs.ci.outputs.XZ_VERSION }}
        artifacts: "dist/*"

  digital-ocean-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Get build artifacts
      uses: actions/download-artifact@v3.0.2
      with:
        name: dist
        path: dist
        
    - name: Publish to Digital Ocean
      uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.ACCESS_KEY}}
        secret_key: ${{ secrets.SECRET_KEY }}
        space_name: ${{ secrets.SPACE_NAME }}
        space_region: ${{ secrets.SPACE_REGION }}
        source: dist